apiVersion: v1
kind: Namespace
metadata:
  name: qa

--- 
apiVersion: v1
kind: Service
metadata: 
  labels: 
    run: my-nginx
  name: my-nginx
  namespace: qa
spec: 
  ports: 
    - 
      port: 80
      protocol: TCP
  selector: 
    run: my-nginx
--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nginx-deployment
spec: 
  replicas: 2
  selector: 
    matchLabels: 
      app: nginx
  template: 
    metadata: 
      labels: 
        app: nginx
    spec: 
      containers: 
        - 
          image: "nginx:1.14.2"
          name: nginx
          ports: 
            - 
              containerPort: 80
